# fly.toml app configuration file generated for your carbon tracking app

app = "carbon-tracker"
primary_region = "dfw"

[build]
  [build.args]
    NODE_VERSION = "18"

[env]
  PORT = "8080"
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    method = "get"
    path = "/api/ping"
    protocol = "http"
    timeout = "2s"
    interval = "15s"
    restart_limit = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[deploy]
  release_command = "npm run build"
